service: nodejs-aws-lambda
provider:
  name: aws
  runtime: nodejs18.x
functions:
  createPayment:
    handler: dist/serverless.handler
    events:
      - http: 'POST /payments'
plugins:
  - serverless-offline
package:
  excludeDevDependencies: true
  exclude:
    - .git/**
    - .vscode/**
    - .terraform/**